### ISSUE TITLE
first derivative on unlabeled data?

### ISSUE THREAD

**Issue by jizongFox** [Sakura03/SemiMeta#1]
Hello, 

Thanks for this great paper. I have checked the detail of your code and the paper, and it seems that you used the labelled loss to firstly get the gradient. This point is different from your description. I still cannot understand why the gradient of the loss between unlabeled prediction and pseudo label is not 0. 

Thanks in advance for your kind reply. 

Jizong

**Comment by Sakura03** [comment]
Hi Jizong,

Thanks for your interest in our paper. Let me make sure that "the gradient from the labeled loss" in your statement refers to `dtheta` in the code (L140 of `train_meta.py`). If so, please check Eq. (10) and (11) of the paper, which is implemented in L142-163 of `train_meta.py`.

Secondly, the gradient of the pseudo-labels can be expanded as in Eq. (8) of the paper. It can be seen that the gradient of the pseudo-labels is not zero as long as the two terms in the RHS of Eq. (8) are not zero. If this explanation is too abstract, you can consider the figure in the left column of our poster (`images/aistats-poster.pdf`). If we give a small perturbation to the pseudo-label, the gradient of parameters (\nabla \theta) will change accordingly (can no longer be zero). This will result in a change of the updated parameters (\tilde{\theta}), leading to a different labeled loss. I hope this could intuitively explain why the gradient of the labeled loss w.r.t. the pseudo-label is not zero.

If you have further questions, don't hesitate to contact me via email (xinyuzhang@mail.nankai.edu.cn).

Best,
Xin-Yu

**Comment by jizongFox** [comment]
Thank @Sakura03 for the detailed reply. 

Thanks to your explanation, I have a decent understanding of your idea. 

Best, 
Jizong
